# Generated by Django 4.0 on 2021-12-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nested_serializer_phone_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
