# Generated by Django 4.0 on 2021-12-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('descriptions', models.CharField(max_length=300)),
                ('ratings', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
