# Generated by Django 4.0 on 2021-12-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ratings',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
